#!/bin/sh
# Control Center installer.
#
#   curl -fsSL https://github.com/mohammadakradi/control-center/releases/latest/download/install.sh -o install.sh
#   less install.sh        # you are about to run a script off the internet — read it
#   sh install.sh
#
# Installs the latest release into ~/.control-center and puts a `control-center` command on
# your PATH. Requires Node.js 22+ and nothing else: no Docker, no pnpm, no git, no clone.
#
# Re-running is safe. Your database, encrypted tokens and .env are in ~/.control-center/data
# and ~/.control-center/.env, and are never overwritten once created.
set -eu

REPO="${CC_REPO:-mohammadakradi/control-center}"
CC_HOME="${CC_HOME:-$HOME/.control-center}"
BIN_DIR="${CC_BIN_DIR:-$HOME/.local/bin}"
MIN_NODE_MAJOR=22

info() { printf '%s\n' "$*"; }
warn() { printf '%s\n' "$*" >&2; }
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# ── prerequisites ───────────────────────────────────────────────────────────────────────
for tool in curl tar; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is required but not installed."
done

command -v node >/dev/null 2>&1 || die "Node.js $MIN_NODE_MAJOR+ is required.
Install it from https://nodejs.org, or with: brew install node   (macOS)
                                             nvm install 22      (any platform)"
node_major=$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)
[ "$node_major" -ge "$MIN_NODE_MAJOR" ] 2>/dev/null ||
  die "Node.js $MIN_NODE_MAJOR+ is required (found $(node -v)). Upgrade and re-run."
info "Node $(node -v) — OK"

# ── which release ───────────────────────────────────────────────────────────────────────
TAG="${CC_VERSION:-}"
if [ -z "$TAG" ]; then
  info "Looking up the latest release of $REPO…"
  TAG=$(curl -fsSL --max-time 15 -H 'Accept: application/vnd.github+json' \
    "https://api.github.com/repos/$REPO/releases/latest" 2>/dev/null |
    sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
fi
[ -n "$TAG" ] || die "couldn't determine the latest release. Set CC_VERSION=v0.1.0 to pin one."
VERSION=${TAG#v}
TARBALL="control-center-$VERSION.tar.gz"
BASE="https://github.com/$REPO/releases/download/$TAG"
info "Installing $VERSION into $CC_HOME"

# ── download + verify ───────────────────────────────────────────────────────────────────
tmp="$CC_HOME/.install.$$"
mkdir -p "$tmp"
# shellcheck disable=SC2064 # expand $tmp now, not at trap time
trap "rm -rf '$tmp'" EXIT INT TERM

curl -fsSL --max-time 300 -o "$tmp/$TARBALL" "$BASE/$TARBALL" || die "download failed: $BASE/$TARBALL"

if curl -fsSL --max-time 30 -o "$tmp/SHA256SUMS" "$BASE/SHA256SUMS" 2>/dev/null; then
  expected=$(sed -n "s/^\([0-9a-f]*\)[[:space:]]*\**$TARBALL\$/\1/p" "$tmp/SHA256SUMS" | head -1)
  if [ -n "$expected" ]; then
    if command -v shasum >/dev/null 2>&1; then
      actual=$(shasum -a 256 "$tmp/$TARBALL" | cut -d' ' -f1)
    elif command -v sha256sum >/dev/null 2>&1; then
      actual=$(sha256sum "$tmp/$TARBALL" | cut -d' ' -f1)
    else
      actual=$expected
      warn "No shasum/sha256sum available — skipping checksum verification."
    fi
    [ "$actual" = "$expected" ] || die "checksum mismatch for $TARBALL — aborting."
    info "Checksum OK."
  fi
fi

# ── unpack + dependencies ───────────────────────────────────────────────────────────────
mkdir -p "$tmp/app"
tar -xzf "$tmp/$TARBALL" -C "$tmp/app" --strip-components=1

info "Installing dependencies (a minute or two — this compiles nothing, it downloads a"
info "prebuilt SQLite binary for your platform)…"
(cd "$tmp/app" && npx --yes "pnpm@${CC_PNPM_VERSION:-9.12.1}" install --frozen-lockfile) ||
  die "dependency install failed."

# ── place it ────────────────────────────────────────────────────────────────────────────
mkdir -p "$CC_HOME/data" "$CC_HOME/logs" "$CC_HOME/run"
if [ -d "$CC_HOME/app" ]; then
  info "Replacing the existing install (keeping data/ and .env)…"
  rm -rf "$CC_HOME/app.old"
  mv "$CC_HOME/app" "$CC_HOME/app.old"
fi
mv "$tmp/app" "$CC_HOME/app"

# ── first-run config ────────────────────────────────────────────────────────────────────
# SECRETS_MASTER_KEY encrypts each user's Anthropic token at rest. Generated once; if it is
# ever lost, stored tokens can't be decrypted and have to be re-entered.
if [ ! -f "$CC_HOME/.env" ]; then
  if command -v openssl >/dev/null 2>&1; then
    key=$(openssl rand -base64 32)
  else
    key=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
  fi
  cat >"$CC_HOME/.env" <<EOF
# Control Center configuration. Generated by install.sh on first install; never overwritten.

# Encrypts each signed-in user's Anthropic token at rest (data/secrets/). Back this up:
# lose it and every stored token must be re-entered.
SECRETS_MASTER_KEY=$key

# Folders the project picker may browse (colon-separated, first = where it opens).
# Defaults to your home directory when unset.
# PROJECT_ROOTS=$HOME:/Volumes

# Lets agents open PRs with gh and push over HTTPS. Create one at
# https://github.com/settings/tokens with 'repo' scope.
# GH_TOKEN=
EOF
  chmod 600 "$CC_HOME/.env"
  info "Generated $CC_HOME/.env with a fresh SECRETS_MASTER_KEY"
fi

# ── database ────────────────────────────────────────────────────────────────────────────
# Creates the schema on a fresh install and applies pending migrations on a re-install. It
# snapshots into data/backup/ before changing anything, and refuses to proceed if the existing
# database doesn't match what this version expects (rather than starting an app that will fail
# on its first query).
info "Setting up the database…"
(
  cd "$CC_HOME/app" &&
    PLATFORM_DATA_DIR="$CC_HOME/data" ./node_modules/.bin/tsx runner/migrate.ts
) || die "database migration failed. Nothing was started; your data is untouched."

# ── the command ─────────────────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
cp "$CC_HOME/app/infra/release/control-center.sh" "$BIN_DIR/control-center"
chmod +x "$BIN_DIR/control-center"
rm -rf "$tmp"
trap - EXIT INT TERM

info ""
info "Installed Control Center $VERSION"
info ""
case ":$PATH:" in
  *":$BIN_DIR:"*)
    info "Start it with:   control-center start"
    ;;
  *)
    warn "$BIN_DIR isn't on your PATH. Either add it:"
    warn "    echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc && exec zsh"
    warn "…or start it with the full path:"
    warn "    $BIN_DIR/control-center start"
    ;;
esac
info ""
info "That command checks for new releases each time it runs, updates if there is one,"
info "starts the app, and opens it in a Chrome app window. Then sign up in the app and add"
info "your Anthropic token under Settings."
